FROM python:3.11-slim

WORKDIR /app

COPY telegram_bot/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY telegram_bot/ ./telegram_bot/

WORKDIR /app/telegram_bot

CMD ["python", "bot.py"]

